name: "Setup anything"
description: "Setup any tools"
author: "Kazuki Suda"
inputs:
  url:
    description: "The URL of the downloaded file"
    required: true
  archive_format:
    description: "The archive format of the downloaded file. One of: zip|tar|tar.gz|tgz|7z|none"
    required: false
    default: "none"
  bin_dir:
    description: "The path of the bin directory"
    required: false
    default: "./"
  test:
    description:  "TODO"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
