name: "Setup anything"
description: "Setup any tools"
author: "Kazuki Suda"
inputs:
  url:
    description: "The URL of the downloaded file"
    required: true
  tool_name:
    description: "The name of the downloaded file"
    required: false
  tool_dir:
    description: "The path of the directory where the tool is located"
    required: false
    default: "./"
  archive_format:
    description: "The archive format of the downloaded file. One of: zip|tar|7z|none"
    required: false
    default: "none"
  test:
    description:  "TODO"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
